---
- name: Check for RHEL security advisories and format the output
  hosts: all
  become: yes
  tasks:
    - name: Run dnf updateinfo to get a list of security updates
      ansible.builtin.command: dnf updateinfo list updates security
      register: dnf_output
      ignore_errors: yes
      changed_when: false

    - name: Set a fact for advisories found
      ansible.builtin.set_fact:
        advisories_found: "{{ dnf_output.stdout | length > 0 }}"

    - name: Format and display the security advisories
      ansible.builtin.debug:
        msg: |
          RHEL Security Advisories Found:
          {% for line in dnf_output.stdout_lines %}
          - Advisory: {{ line.split()[0] }}
            Severity: {{ line.split()[1] }}
            Packages: {{ ' '.join(line.split()[2:]) }}
          {% endfor %}
      when: advisories_found

    - name: No security advisories found
      ansible.builtin.debug:
        msg: "✅ No new security advisories found on the system. The system is up to date."
      when: not advisories_found
