---
- name: Count RHEL security advisories by severity
  hosts: all
  become: yes
  vars:
    # Define the desired order for severity levels
    severity_order:
      - Critical
      - Important
      - Moderate
      - Low

  tasks:
    - name: Run dnf updateinfo to get a list of security updates
      ansible.builtin.command: " sudo dnf updateinfo list updates security | grep 'Important' | wc -l "
      register: dnf_output
      ignore_errors: yes
      changed_when: false


    - name: Display the total count of advisories
      ansible.builtin.debug:
        msg: "Total Security Advisories Found: {{ dnf_output }}"
      when: dnf_output is defined
