---
- name: Count security advisories by severity
  hosts: all
  become: yes
  vars:
    severities:
      - Critical
      - Important
      - Moderate
      - Low

  tasks:
    - name: Get advisory counts for each severity
      ansible.builtin.shell: |
        declare -A counts
        for severity in "{{ severities | join(' ') }}"; do
          count=$(dnf updateinfo list updates security | grep -c "$severity")
          counts["$severity"]=$count
        done
        for severity in "${!counts[@]}"; do
          echo "$severity:${counts[$severity]}"
        done
      register: advisory_counts
      changed_when: false

    - name: Display advisory counts
      ansible.builtin.debug:
        msg: |
          Security Advisories by Severity:
          {% for line in advisory_counts.stdout_lines %}
            {% set parts = line.split(':') %}
            - {{ parts[0] }}: {{ parts[1] }}
          {% endfor %}
